services:
  opencode-api:
    image: hk59775634/opencode-api:latest
    ports:
      - "80:80"
    environment:
      - API_KEY=${API_KEY:-} # 不设置API_KEY则免鉴权 如果设置按照这个格式填写：- API_KEY=${API_KEY:-sk-mykey} 
